server:
  port: 8090
#friend: {name: robin,age: 18,childrenName: [yiyi,xixi]}
person:
  lastName: robin
  age: 18
  birth: 1993/10/18
  children:
    - name: ${person.lastName12:jinglan}_yiyi
      age: 2
    - name: xixi
      age: 1
  maps:
    yiyi: yiyi
    xixi: xixi